// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNfzZMNGKUNwq9bn_ZQhJFifxYwgvROmE',
    appId: '1:977978511589:web:653298901f41ac70dfc40c',
    messagingSenderId: '977978511589',
    projectId: 'fines-app-f2eed',
    authDomain: 'fines-app-f2eed.firebaseapp.com',
    storageBucket: 'fines-app-f2eed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE2MV9OS85u4E3Y4YGuprOiHil85zJNCM',
    appId: '1:977978511589:android:07b9dbe74332c6a5dfc40c',
    messagingSenderId: '977978511589',
    projectId: 'fines-app-f2eed',
    storageBucket: 'fines-app-f2eed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDhxs_OjsWqbDCeneGvswfpOVUBZvb9Z8',
    appId: '1:977978511589:ios:d5183f13fe78335fdfc40c',
    messagingSenderId: '977978511589',
    projectId: 'fines-app-f2eed',
    storageBucket: 'fines-app-f2eed.firebasestorage.app',
    iosBundleId: 'com.example.fitnesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNfzZMNGKUNwq9bn_ZQhJFifxYwgvROmE',
    appId: '1:977978511589:web:1d38b7de9aca3befdfc40c',
    messagingSenderId: '977978511589',
    projectId: 'fines-app-f2eed',
    authDomain: 'fines-app-f2eed.firebaseapp.com',
    storageBucket: 'fines-app-f2eed.firebasestorage.app',
  );
}
